version: "3"
services:
  mongodb:
    container_name: 'mongodb'
    image: 'mongo:latest'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: